version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-deps:
        patterns:
          - '*'
    labels:
      - actions
      - dependencies

  - package-ecosystem: npm
    directory: /src
    schedule:
      interval: monthly
    groups:
      npm-deps-major:
        dependency-type: production
        update-types:
          - major
      npm-deps-minor-and-patches:
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-deps-dev-major:
        dependency-type: development
        update-types:
          - major
      npm-deps-dev-minor-and-patches:
        dependency-type: development
        update-types:
          - minor
          - patch
    labels:
      - npm
      - dependencies

  - package-ecosystem: composer
    directory: /src
    schedule:
      interval: monthly
    groups:
      composer-deps-major:
        dependency-type: production
        update-types:
          - major
      composer-deps-minor-and-patches:
        dependency-type: production
        update-types:
          - minor
          - patch
      composer-deps-dev-major:
        dependency-type: development
        update-types:
          - major
      composer-deps-dev-minor-and-patches:
        dependency-type: development
        update-types:
          - minor
          - patch
    labels:
      - composer
      - dependencies
