name: deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Install PHP dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --working-dir src

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install NodeJS dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: npm install --prefix src

      - name: Build assets
        working-directory: src
        run: npm run build

      - name: Generate .env file
        working-directory: src
        run: |
          cat <<EOL > .env
          APP_NAME=Placemonkeys
          APP_ENV=production
          APP_KEY=${{ secrets.ENV_APP_KEY }}
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_URL=https://www.placemonkeys.com
          
          APP_LOCALE=en
          APP_FALLBACK_LOCALE=en
          APP_FAKER_LOCALE=en_US
          
          APP_MAINTENANCE_DRIVER=file
          
          BCRYPT_ROUNDS=12
          
          LOG_CHANNEL=daily
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug
          
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          
          QUEUE_CONNECTION=sync
          
          CACHE_STORE=file
          CACHE_PREFIX=
          
          VITE_APP_NAME="${APP_NAME}"
          EOL

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Debug - Test SSH connection
        run: ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }} "echo 'SSH connection successful'"

      - name: Deploy to remote server
        run: |
          rsync -avzc --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            --exclude='node_modules' \
            ./src/ ${{ secrets.SSH_REMOTE_USER }}@${{ secrets.SSH_REMOTE_HOST }}:${{ vars.REMOTE_WORKDIR }}
